import { StyleSheet } from 'react-native';
import { colors, radius } from './theme';

export const ui = StyleSheet.create({
  /* Cabeceras */
  header: { paddingHorizontal: 16, paddingTop: 12, paddingBottom: 14, borderBottomLeftRadius: 16, borderBottomRightRadius: 16 },
  headerTeal: { backgroundColor: colors.teal },
  headerTealDark: { backgroundColor: colors.tealDark },
  headerPurple: { backgroundColor: colors.purple },
  headerRust: { backgroundColor: colors.rust },
  back: { color: colors.white, fontWeight: '700', fontSize: 13, marginBottom: 6 },
  title: { fontSize: 20, fontWeight: '800', color: colors.white, marginBottom: 8 },
  sub: { fontSize: 10, color: colors.white, opacity: 0.9, letterSpacing: 1, marginBottom: 10 },
  search: { borderWidth: 2, borderColor: colors.white, borderRadius: radius.sm, paddingVertical: 8, paddingHorizontal: 12, fontSize: 13, color: colors.ink, backgroundColor: colors.surface, marginBottom: 10 },
  btnsRow: { flexDirection: 'row', justifyContent: 'flex-end', marginBottom: 8 },
  headerBtn: { paddingVertical: 6, paddingHorizontal: 10, borderRadius: 6, backgroundColor: colors.white },
  /* Tabs */
  tabsWrap: { flexDirection: 'row', alignItems: 'center', flexWrap: 'wrap' },
  tabsRow: { flexDirection: 'row', alignItems: 'center', paddingRight: 8 },
  tab: { paddingVertical: 6, paddingHorizontal: 12, borderRadius: 999, borderWidth: 1, borderColor: colors.line, backgroundColor: colors.surface, marginRight: 6, marginBottom: 4 },
  tabActiveTeal: { backgroundColor: colors.teal, borderColor: colors.teal },
  tabActivePurple: { backgroundColor: colors.purple, borderColor: colors.purple },
  tabText: { fontSize: 11, fontWeight: '600', color: colors.steel },
  tabTextActive: { color: colors.white },
  /* Listas / vacíos */
  list: { padding: 8, paddingBottom: 100 },
  empty: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: 30 },
  emptyIcon: { fontSize: 40, marginBottom: 10 },
  emptyText: { fontSize: 13, color: colors.steel, textAlign: 'center', marginTop: 10 },
  /* Tarjeta de producto */
  card: { backgroundColor: colors.surface, borderWidth: 2, borderColor: colors.ink, borderRadius: radius.md, overflow: 'hidden', flex: 1, margin: 6, minWidth: 150, maxWidth: 400 },
  categoryTag: { position: 'absolute', top: 8, right: 8, borderRadius: 4, paddingVertical: 3, paddingHorizontal: 7, zIndex: 3 },
  tagMaterial: { backgroundColor: colors.purple }, 
tagHerramienta: { backgroundColor: colors.teal },   
  categoryTagText: { color: colors.white, fontSize: 8, fontWeight: '700', letterSpacing: 0.5 },
  photoWrap: { height: 110, backgroundColor: colors.hole, justifyContent: 'center', alignItems: 'center', borderBottomWidth: 2, borderBottomColor: colors.steel, borderStyle: 'dashed' },
  photo: { width: '100%', height: '100%' },
  photoPlaceholder: { alignItems: 'center', justifyContent: 'center' },
  photoPlaceholderText: { color: colors.steel, fontSize: 11, letterSpacing: 1 },
  cardBody: { padding: 12 },
  cardName: { fontSize: 13, fontWeight: '800', color: colors.ink, textTransform: 'uppercase', marginBottom: 8 },
  qtyBox: { borderWidth: 2, borderColor: colors.ink, borderRadius: 4, paddingVertical: 6, alignItems: 'center', backgroundColor: colors.surface },
  qtyNum: { fontSize: 18, fontWeight: '800', color: colors.ink },
  qtyLabel: { fontSize: 9, color: colors.steel, textTransform: 'uppercase', letterSpacing: 1, textAlign: 'center', marginTop: 4, marginBottom: 8 },
  chip: { paddingHorizontal: 10, paddingVertical: 5, borderRadius: 14, backgroundColor: colors.hole, borderWidth: 1, borderColor: colors.line },
  chipText: { fontSize: 11, fontWeight: '700', color: colors.ink },
  markBtn: { marginTop: 10, borderWidth: 2, borderColor: colors.rust, borderRadius: 6, paddingVertical: 8, alignItems: 'center', backgroundColor: colors.surface },
  markBtnText: { color: colors.rust, fontWeight: '800', fontSize: 12, textTransform: 'uppercase' },
  dangerSolidBtn: { backgroundColor: colors.rust, borderRadius: 6, paddingVertical: 10, alignItems: 'center' },
  dangerSolidBtnText: { color: colors.white, fontWeight: '800', fontSize: 13, textTransform: 'uppercase' },
  /* Tarjetas grandes */
  bigRow: { flexDirection: 'row', justifyContent: 'center', flexWrap: 'wrap', paddingHorizontal: 12 },
  bigCard: { width: '44%', minWidth: 160, maxWidth: 280, margin: 8, backgroundColor: colors.surface, borderWidth: 2, borderColor: colors.purple, borderRadius: radius.md, overflow: 'hidden' },
  bigCardTop: { height: 95, backgroundColor: colors.hole, alignItems: 'center', justifyContent: 'center', borderBottomWidth: 2, borderBottomColor: colors.purple, borderStyle: 'dashed' },
  bigBadge: { position: 'absolute', top: 8, right: 8, borderRadius: 4, paddingVertical: 3, paddingHorizontal: 8 },
  bigBadgeText: { color: colors.white, fontSize: 10, fontWeight: '800' },
  bigCardBody: { padding: 12, alignItems: 'center' },
  bigCardTitle: { fontSize: 14, fontWeight: '800', color: colors.ink, textAlign: 'center', textTransform: 'uppercase' },
  bigCardDesc: { fontSize: 11, color: colors.steel, textAlign: 'center', marginTop: 6 },
  /* FAB */
  fab: { position: 'absolute', right: 20, bottom: 24, width: 56, height: 56, borderRadius: 28, alignItems: 'center', justifyContent: 'center', elevation: 4, zIndex: 5 },
  fabPurple: { backgroundColor: colors.purple },
  fabRust: { backgroundColor: colors.rust },
  fabText: { fontSize: 28, color: colors.white, fontWeight: '700', lineHeight: 30 },
  /* Formularios / modales */
  label: { fontSize: 11, fontWeight: '800', color: colors.steel, letterSpacing: 1, marginBottom: 6, textTransform: 'uppercase' },
  modalLabel: { fontSize: 11, fontWeight: '800', color: colors.ink, letterSpacing: 1, marginBottom: 8, textTransform: 'uppercase' },
  input: { borderWidth: 2, borderColor: colors.ink, borderRadius: radius.sm, paddingVertical: 10, paddingHorizontal: 12, fontSize: 14, color: colors.ink, marginBottom: 10, backgroundColor: colors.surface },
  fieldInput: { borderWidth: 2, borderColor: colors.ink, borderRadius: radius.sm, paddingVertical: 10, paddingHorizontal: 12, fontSize: 13, color: colors.ink, marginBottom: 14, backgroundColor: colors.surface },
  amountInput: { borderWidth: 2, borderColor: colors.ink, borderRadius: radius.sm, paddingVertical: 10, paddingHorizontal: 12, fontSize: 16, fontWeight: '700', color: colors.ink, textAlign: 'center', marginBottom: 14, backgroundColor: colors.surface },
  inputError: { borderColor: colors.rust },
  errorText: { color: colors.rust, fontSize: 11, fontWeight: '700', marginBottom: 8 },
  dropdown: { borderWidth: 2, borderColor: colors.teal, borderRadius: radius.sm, backgroundColor: colors.surface, marginBottom: 10 },
  listItem: { paddingVertical: 10, paddingHorizontal: 12, borderBottomWidth: 1, borderBottomColor: colors.hole },
  listItemText: { fontSize: 13, fontWeight: '600', color: colors.ink },
  emptyHint: { fontSize: 11, color: colors.steel, padding: 10, textAlign: 'center' },
  chipRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 6, marginBottom: 12 },
  selChip: { paddingHorizontal: 12, paddingVertical: 7, borderRadius: 16, borderWidth: 1, borderColor: colors.line, backgroundColor: colors.surface },
  selChipActive: { backgroundColor: colors.purple, borderColor: colors.purple },
  selChipActiveTeal: { backgroundColor: colors.teal, borderColor: colors.teal },
  selChipText: { fontSize: 12, fontWeight: '600', color: colors.steel },
  selChipTextActive: { color: colors.white, fontWeight: '700' },
  priceRow: { flexDirection: 'row', borderWidth: 2, borderColor: colors.ink, borderRadius: radius.sm, overflow: 'hidden', marginBottom: 10 },
  currBtn: { backgroundColor: colors.rust, paddingHorizontal: 12, justifyContent: 'center' },
  currText: { color: colors.white, fontWeight: '800', fontSize: 12 },
  priceInput: { flex: 1, minWidth: 0, paddingVertical: 10, paddingHorizontal: 10, fontSize: 13, color: colors.ink, textAlign: 'right' },
  actions: { flexDirection: 'row', gap: 10 },
  btn: { flex: 1, paddingVertical: 12, borderRadius: radius.sm, alignItems: 'center', borderWidth: 2, borderColor: colors.ink },
  btnText: { fontWeight: '700', fontSize: 13, textTransform: 'uppercase', color: colors.ink },
  btnCancel: { backgroundColor: colors.surface },
  btnOk: { backgroundColor: colors.teal, borderColor: colors.tealDark },
  btnDanger: { backgroundColor: colors.rust, borderColor: colors.rust },
  btnWhiteText: { color: '#fff' },
});